"""Name generation primitives."""

from __future__ import annotations

import random
from collections.abc import Sequence

DEFAULT_NOUNS: tuple[str, ...] = (
    "abatement",
    "abeyance",
    "acquit",
    "adjournment",
    "advocacy",
    "advocate",
    "affidavit",
    "affirmation",
    "agreement",
    "allocution",
    "annulment",
    "appeal",
    "arbiter",
    "arbitration",
    "arraignment",
    "assize",
    "attachment",
    "attestation",
    "bail",
    "bailiff",
    "bailiwick",
    "bailment",
    "bailor",
    "banc",
    "bankruptcy",
    "bar",
    "barrister",
    "bench",
    "beneficiary",
    "bequeath",
    "bequest",
    "blackacre",
    "bond",
    "bondsman",
    "brief",
    "briefing",
    "bylaw",
    "cadastre",
    "capias",
    "caseload",
    "causation",
    "caveat",
    "certiorari",
    "chambers",
    "chancellor",
    "chancery",
    "charter",
    "chattel",
    "citation",
    "claimant",
    "clause",
    "clerk",
    "code",
    "codex",
    "codicil",
    "colloquy",
    "commission",
    "commissioner",
    "consent",
    "consideration",
    "contract",
    "conveyance",
    "corpus",
    "counsel",
    "counselor",
    "courtroom",
    "covenant",
    "curator",
    "custody",
    "damages",
    "dative",
    "decree",
    "deed",
    "defendant",
    "defense",
    "delegate",
    "deliberation",
    "demurrer",
    "depose",
    "devisee",
    "dictum",
    "disclosure",
    "discovery",
    "dissent",
    "docket",
    "doctrine",
    "dossier",
    "dower",
    "duty",
    "easement",
    "ejectment",
    "emolument",
    "enactment",
    "engrossment",
    "equity",
    "escheat",
    "escrow",
    "esquire",
    "estate",
    "estoppel",
    "evidence",
    "examiner",
    "exchequer",
    "executor",
    "exhibit",
    "fealty",
    "fee",
    "fiduciary",
    "filiation",
    "finding",
    "forbearance",
    "foreclosure",
    "foreman",
    "forum",
    "franchise",
    "freehold",
    "gavel",
    "grantee",
    "grantor",
    "guardian",
    "guardianship",
    "habeas",
    "habendum",
    "hearing",
    "heirloom",
    "heirship",
    "holder",
    "holding",
    "homestead",
    "honor",
    "impleader",
    "indenture",
    "injunction",
    "inquest",
    "insolvency",
    "interpleader",
    "interrogatory",
    "jetsam",
    "jettison",
    "joinder",
    "jointure",
    "judgment",
    "judicature",
    "juror",
    "jurisdiction",
    "jurisprudence",
    "jurist",
    "jury",
    "justice",
    "justiciary",
    "keeper",
    "kindred",
    "laches",
    "lease",
    "leasehold",
    "ledger",
    "legacy",
    "legatee",
    "legitimacy",
    "levy",
    "licensee",
    "lien",
    "lienor",
    "litigant",
    "litigation",
    "litigator",
    "livery",
    "magistrate",
    "maintenance",
    "mandate",
    "marshal",
    "maxim",
    "mediator",
    "memo",
    "merit",
    "misfeasance",
    "moiety",
    "moot",
    "mortgage",
    "mortgagee",
    "mortgagor",
    "motion",
    "naturalization",
    "nonage",
    "nonsuit",
    "notarization",
    "notarize",
    "notary",
    "novation",
    "nullity",
    "oath",
    "obiter",
    "objection",
    "obligation",
    "obligee",
    "occupancy",
    "ombudsman",
    "ordinance",
    "ordinary",
    "orator",
    "outlaw",
    "pact",
    "pardon",
    "parol",
    "partition",
    "patent",
    "pedigree",
    "petition",
    "petitioner",
    "plaintiff",
    "plea",
    "plead",
    "pleader",
    "pleading",
    "possession",
    "preamble",
    "precedent",
    "presentment",
    "primogeniture",
    "probate",
    "proceeding",
    "proclamation",
    "procurator",
    "provision",
    "proxy",
    "quarantine",
    "quash",
    "quitclaim",
    "quorum",
    "ratification",
    "ratify",
    "realty",
    "rebuttal",
    "recess",
    "recital",
    "recognizance",
    "record",
    "recorder",
    "recuse",
    "redress",
    "referee",
    "register",
    "registry",
    "regulation",
    "remainder",
    "remedy",
    "replevin",
    "reporter",
    "rescission",
    "respondent",
    "restitution",
    "retainer",
    "reverter",
    "review",
    "ruling",
    "salvage",
    "sanction",
    "sanctuary",
    "scribe",
    "seal",
    "seisin",
    "sequestration",
    "session",
    "settlement",
    "sidebar",
    "silk",
    "solicitor",
    "sovereign",
    "statute",
    "statutory",
    "stipulation",
    "sublease",
    "subpoena",
    "subrogation",
    "summation",
    "summons",
    "surety",
    "suretyship",
    "tacit",
    "tenancy",
    "tenant",
    "tender",
    "tenure",
    "testacy",
    "testator",
    "testimony",
    "title",
    "tort",
    "tortfeasor",
    "treaty",
    "trial",
    "tribunal",
    "trover",
    "trust",
    "trustee",
    "ultimatum",
    "underwriter",
    "unity",
    "university",
    "usage",
    "usufruct",
    "usury",
    "utility",
    "vacatur",
    "vendee",
    "vendor",
    "venire",
    "venue",
    "verdict",
    "vested",
    "vesting",
    "vicinage",
    "voucher",
    "wager",
    "waif",
    "waiver",
    "ward",
    "warden",
    "wardship",
    "warrant",
    "warrantee",
    "warrantor",
    "warranty",
    "waybill",
    "witness",
    "writ",
    "zoning",
)

DEFAULT_DESCRIPTORS: tuple[str, ...] = (
    "agile",
    "ample",
    "balmy",
    "blue",
    "bold",
    "breezy",
    "bright",
    "brisk",
    "bubbly",
    "buoyant",
    "calm",
    "candid",
    "cheery",
    "chipper",
    "chirpy",
    "classy",
    "clever",
    "cozy",
    "crafty",
    "crispy",
    "dainty",
    "dapper",
    "dashing",
    "deft",
    "dreamy",
    "eager",
    "earnest",
    "elated",
    "fancy",
    "festive",
    "fluffy",
    "frisky",
    "frolicsome",
    "funky",
    "fuzzy",
    "gallant",
    "genial",
    "gentle",
    "giddy",
    "gleeful",
    "groovy",
    "gutsy",
    "happy",
    "hardy",
    "hearty",
    "honest",
    "jaunty",
    "jazzy",
    "jolly",
    "jovial",
    "joyful",
    "jumpy",
    "keen",
    "kindly",
    "lively",
    "loud",
    "lucid",
    "lucky",
    "mellow",
    "merry",
    "neat",
    "nifty",
    "nimble",
    "peachy",
    "peppy",
    "perky",
    "placid",
    "plucky",
    "proud",
    "prudent",
    "puffy",
    "quaint",
    "quick",
    "radiant",
    "red",
    "rosy",
    "sassy",
    "savvy",
    "serene",
    "sharp",
    "shiny",
    "silky",
    "silly",
    "sleek",
    "smiley",
    "smooth",
    "snappy",
    "snazzy",
    "snug",
    "sparkly",
    "spicy",
    "spiffy",
    "sprightly",
    "spry",
    "squeaky",
    "squiggly",
    "stately",
    "sterling",
    "stellar",
    "sturdy",
    "suave",
    "sunny",
    "swift",
    "tangy",
    "tidy",
    "trusty",
    "twinkly",
    "upbeat",
    "valiant",
    "vibrant",
    "vivid",
    "wacky",
    "warm",
    "whimsical",
    "wiggly",
    "winsome",
    "witty",
    "zealous",
    "zesty",
    "zippy",
)


def generate_name(
    *,
    descriptors: Sequence[str] = DEFAULT_DESCRIPTORS,
    nouns: Sequence[str] = DEFAULT_NOUNS,
    rng: random.Random | None = None,
    separator: str = "-",
    number_min: int = 1,
    number_max: int = 99,
    number_width: int = 2,
) -> str:
    """Generate one friendly name."""
    _validate_words("descriptors", descriptors)
    _validate_words("nouns", nouns)

    if not separator:
        raise ValueError("separator must not be empty")
    if number_min > number_max:
        raise ValueError("number_min must be less than or equal to number_max")
    if number_width < 1:
        raise ValueError("number_width must be at least 1")

    if rng is None:
        descriptor = random.choice(descriptors)
        noun = random.choice(nouns)
        number = random.randint(number_min, number_max)
    else:
        descriptor = rng.choice(descriptors)
        noun = rng.choice(nouns)
        number = rng.randint(number_min, number_max)

    return separator.join((descriptor, noun, f"{number:0{number_width}d}"))


def generate_session_name(
    *,
    descriptors: Sequence[str] = DEFAULT_DESCRIPTORS,
    nouns: Sequence[str] = DEFAULT_NOUNS,
    rng: random.Random | None = None,
    separator: str = "-",
    number_min: int = 1,
    number_max: int = 99,
    number_width: int = 2,
) -> str:
    """Generate one friendly session name."""
    return generate_name(
        descriptors=descriptors,
        nouns=nouns,
        rng=rng,
        separator=separator,
        number_min=number_min,
        number_max=number_max,
        number_width=number_width,
    )


def generate_combination() -> str:
    """Generate one name using the original Kelvin helper name."""
    return generate_session_name()


def _validate_words(label: str, words: Sequence[str]) -> None:
    if not words:
        raise ValueError(f"{label} must contain at least one word")
